/* The console does not redraw the package. It CARRIES it.
   Every module the sidebar lists is gzipped and embedded verbatim; the console
   decompresses one on demand and shows the real, designed file inside itself,
   on the same origin — so the module reads and writes the very same SL_*
   channels the console reads. That sharing IS the wiring. */
import { readFileSync, writeFileSync, readdirSync } from 'node:fs';
import { gzipSync } from 'node:zlib';
import { join } from 'node:path';

const SRC = '/home/claude/work';
const OUT = new URL('../src/lib/modules_html.ts', import.meta.url).pathname;

const files = readFileSync(new URL('../src/lib/modules.ts', import.meta.url).pathname, 'utf8')
  .match(/ShopyLink_[A-Za-z0-9_]+\.html/g);
const wanted = [...new Set(files)].sort();

const present = new Set(readdirSync(SRC));
const missing = wanted.filter(f => !present.has(f));
if (missing.length) {
  console.error('MISSING module files: ' + missing.join(', '));
  process.exit(1);
}

let total = 0;
const rows = wanted.map(f => {
  const raw = readFileSync(join(SRC, f));
  const gz = gzipSync(raw, { level: 9 });
  const b64 = gz.toString('base64');
  total += b64.length;
  console.log(`  ${f}: ${(raw.length / 1024).toFixed(0)}KB -> ${(b64.length / 1024).toFixed(0)}KB b64`);
  return `  '${f}': '${b64}',`;
});

const out = `/* GENERATED by tools/embed_modules.mjs — do not edit by hand.
   The package's own module files, gzipped and base64'd, verbatim. Nothing here
   is redrawn: the console shows each file as its authors built it. */
export const MODULE_GZ: Record<string, string> = {
${rows.join('\n')}
};
export const MODULE_FILES = Object.keys(MODULE_GZ);
`;
writeFileSync(OUT, out);
console.log(`\n${wanted.length} modules embedded · ${(total / 1024 / 1024).toFixed(2)}MB base64 -> ${OUT}`);
