const fs=require('fs');const {JSDOM,VirtualConsole}=require('/home/claude/work/node_modules/jsdom');
const dom=new JSDOM(fs.readFileSync('ShopyLink_D1_Control.html','utf8'),{runScripts:'dangerously',pretendToBeVisual:true,virtualConsole:new VirtualConsole()});
const w=dom.window,d=w.document;const sh=()=>d.getElementById('shell').innerHTML;
let f=0,n=0;const ok=(c,m)=>{n++;console.log((c?'  ✓ ':'  ✗ FAIL ')+m);if(!c)f++;};

console.log('§76 quick create');
ok(/New</.test(sh()),'76.1 a + New button sits in the bar on every screen');
ok(w.QC_KINDS.length===5,'76.2 five things can be created: work item, client, message, trip cost, shift note');
w.toggleQC();
ok(/Quick create|إنشاء سريع/.test(sh()),'76.3 the panel opens');
let r=w.quickCreateThing('work',{ref:'SL-9603'});
ok(r.ok===false&&r.need.length>0,'76.4 it refuses a half-thing and names every field it still needs');
ok(r.need.indexOf('role')>-1&&r.need.indexOf('due')>-1,'76.4b …including the owner and the due date — the three fields rule holds here too');
const before=w.openItems().length;
r=w.quickCreateThing('work',{ref:'SL-9603',role:'docs',hub:'DAM',next:'chase the chamber',due:6});
ok(r.ok===true&&w.openItems().length===before+1,'76.5 a complete one is created');
const made=w.itemById(r.id);
ok(made.owner==='U-01'&&made.due&&made.next,'76.6 …owned by whoever holds that role at that hub, with a next action and a due date');
r=w.quickCreateThing('client',{name:'Bar Co',country:'Syria',contact:'x'});
ok(r.ok===false&&r.need.indexOf('phone or email')>-1,'76.7 a client still needs a way to be reached');
r=w.quickCreateThing('message',{ref:'SL-9603',roles:['ops'],text:'created from the plus button'});
ok(r.ok===true,'76.8 a message can be created from here — and still obeys record + role');
r=w.quickCreateThing('message',{ref:'SL-9603',text:'no role'});
ok(r.ok===false,'76.8b …it is not a back door around the rule');
w.sim='s8';w.CHAT_REF='SL-9603';
ok(w.qcContext().ref==='SL-9603','76.9 it is context aware — on a thread it pre-fills that record');
w.sim='s0';

console.log('§77 the notice board');
w.setActor('U-01');   /* a notice board is read by somebody: nobody sees only the public ones */
ok(w.NOTICES.length>=3,'77.1 management can post to everyone');
ok(w.noticeLive().length===w.NOTICES.length,'77.2 nothing is dismissed to begin with');
w.go('s0');
ok(/From management|من الإدارة/.test(sh()),'77.3 it sits on My Day where it is read');
const one=w.NOTICES[0].id;
w.dismissNotice(one);
ok(w.noticeLive().length===w.NOTICES.length-1,'77.4 dismissing hides it');
ok(w.noticeArchive().some(x=>x.id===one),'77.5 …but it is kept, not deleted');
ok(/dismissed — kept, not deleted|مُخفاة/.test(sh()),'77.5b …and the archive says so');
w.restoreNotice(one);
ok(w.noticeLive().length===w.NOTICES.length,'77.6 it can be brought back');
const seen1=w.noticeLive().length;
w.setActor('U-03');
ok(w.noticeLive().some(x=>x.id===one),'77.7 dismissal is per user — another person still sees the one you hid');
w.setActor('U-01');
ok(w.postNotice('advisory','x','x','docs').ok===false,'77.8 only the manager posts to the board');
w.setActor('U-00');
ok(w.postNotice('advisory','short','x','manager').ok===false,'77.9 a notice nobody can act on is refused');
ok(w.postNotice('advisory','Port of Lattakia is closed on Friday for maintenance','ميناء اللاذقية مغلق الجمعة للصيانة','manager').ok===true,'77.10 a real one posts');
w.setActor('U-01');

console.log('§78 profile and preferences');
w.go('s9');
ok(/Preferences|التفضيلات/.test(sh()),'78.1 a profile page exists');
ok(new RegExp(w.roleById(w.ME.role).stmt.slice(0,30)).test(sh()),'78.2 it carries the role responsibility statement');
ok(/viewBox="0 0 24 24"/.test(sh())&&/Damascus|دمشق/.test(sh()),'78.3 …and the person\'s hub, with our pin icon');
ok(/mine only|شخصية فقط/.test(sh()),'78.4 it states that company settings live elsewhere — personal and admin are not mixed');
w.setPref('density','compact');
ok(w.density==='compact','78.5 density is a real preference, not decoration');
w.setPref('density','comfortable');
w.setPref('lang','ar');
ok(w.currentLang==='ar'&&d.documentElement.dir==='rtl','78.6 language switches the whole shell');
w.setPref('lang','en');
const nr=w.setNotifyPref('cutoff',false);
ok(nr.ok===false&&/cannot be switched off/.test(nr.why),'78.7 the critical cutoff alert CANNOT be switched off — only resolved');
ok(w.setNotifyPref('message',false).ok===true&&w.PREFS.notify.message===false,'78.8 the others can be');
ok(/cannot be switched off|لا يمكن إطفاؤه/.test(sh()),'78.9 …and the screen says which is locked');
ok(w.myActivity().length>=0,'78.10 a personal activity log exists');
ok(/out of office|إجازة/.test(sh()),'78.11 out-of-office lives on the profile too, where people look for it');

console.log('§80 writing a notice — where, and by whom');
w.setActor('U-01');w.go('s0');
ok(!/only the manager writes here|الكتابة هنا للمدير وحده/.test(sh()),'80.1 a non-manager is told NOTHING about it — no explanation');
ok(!/write a notice/.test(sh()),'80.2 …and no control either; they simply read the board');
ok(w.postNotice('advisory','trying it anyway','x','docs').ok===false,'80.3 and the rule is in the engine, so there is nothing to find');
w.setActor('U-00');w.render();
ok(/write a notice|اكتب إعلانًا/.test(sh()),'80.4 the manager gets the control');
w.toggleNB();
ok(/Post to everyone|انشر للجميع/.test(sh()),'80.5 the composer opens on the board itself, where the notices are');
ok(/English/.test(sh())&&/العربية/.test(sh()),'80.6 it asks for both languages side by side');
const n0=w.NOTICES.length;
w.nbSet('en','x');
ok(w.postNotice('advisory','x','','manager').ok===false,'80.7 a scrap of text is refused');
const r1=w.postNotice('advisory','Beirut port strike expected Thursday, reroute anything urgent','','manager');
ok(r1.ok===true&&r1.notice.untranslated===true,'80.8 one language gets an urgent advisory out — and is MARKED untranslated');
w.render();
ok(/untranslated|غير مترجم/.test(sh()),'80.8b …and the board shows that mark, so nobody thinks the Arabic is missing by accident');
ok(w.NOTICES[0].ar===w.NOTICES[0].en,'80.8c …reading the written language in both places rather than showing blank');
const r2=w.postNotice('policy','All Guangzhou bookings need the new pickup form','كل حجوزات غوانزو تحتاج نموذج الاستلام الجديد','manager');
ok(r2.ok===true&&!r2.notice.untranslated,'80.9 both languages posts clean');
ok(w.NOTICES.length===n0+2,'80.10 both are on the board');
w.nbKind('closure');
ok(w.nbDraft.kind==='closure','80.11 the kind is chosen — advisory, policy or closure');
w.setActor('U-01');w.render();
ok(w.postNotice('advisory','trying to post as documentation officer','x','docs').ok===false,'80.12 the rule holds at the engine, not only in the interface');

console.log('§79 standing rules');
const warm=['write a notice','only the manager writes here','one language is enough in a hurry — it will be marked untranslated','it refuses to create a half-thing — every field it asks for, it needs','dismissed — kept, not deleted','mine only · company settings live under Admin','a critical cutoff alert cannot be switched off — only resolved'];
ok(warm.filter(s=>!w.T_w[s]).length===0,'79.1 every warm string has an Arabic twin');
w.setLang('ar');w.go('s0');
ok(/من الإدارة/.test(sh()),'79.1b AR renders');
w.setLang('en');
ok(/class="machine"/.test(sh()),'79.2 machine values LTR-isolated');
console.log('\n'+(f?('FAIL — '+f+' of '+n):('ALL PASS — '+n+' checks')));
process.exit(f?1:0);
