const fs=require('fs');const {JSDOM,VirtualConsole}=require('/home/claude/work/node_modules/jsdom');
const dom=new JSDOM(fs.readFileSync('ShopyLink_D1_Control.html','utf8'),{runScripts:'dangerously',pretendToBeVisual:true,virtualConsole:new VirtualConsole()});
const w=dom.window,d=w.document;const sh=()=>d.getElementById('shell').innerHTML;
let f=0,n=0;const ok=(c,m)=>{n++;console.log((c?'  ✓ ':'  ✗ FAIL ')+m);if(!c)f++;};
const D=w.DAY;

console.log('§23 deduplicate first');
ok(typeof w.matchClient==='function','23.1 a match function exists and runs before creation');
ok(w.diceScore('تك لاين','التكلاين')>=85,'23.2 Arabic: spacing and the article do not defeat the match');
ok(w.diceScore('Tech Line','TECHLINE')>=85&&w.diceScore('TechLine Trading','Techline')>=85,'23.2b Latin: case, spacing and the legal suffix do not either');
ok(w.matchClient({name:'Completely Other',tax:'SY 99120'})[0].client.id==='CL-001','23.3 the tax number matches decisively whatever the name');
ok(w.normPhone('+963944111222')===w.normPhone('00963 944 111 222')&&w.normPhone('0944 111 222')===w.normPhone('+963944111222'),'23.4 phones match across formats and country-code styles');
const ms=w.matchClient({name:'Sham',phone:'+963 944 111 222'});
ok(ms[0].score>=ms[ms.length-1].score,'23.5 matches are scored and ordered, best first');
let r=w.quickCreate({name:'Tech Line Trading',country:'Syria',contact:'x',phone:'+963 999 000 111'});
ok(r.ok===false&&r.duplicate.length>0,'23.6 a strong match blocks silent creation');
r=w.quickCreate({name:'Tech Line Trading',country:'Syria',contact:'x',phone:'+963 999 000 111'},'different owner, separate legal entity');
ok(r.ok===true,'23.6b …and is released only by a written reason');
const weak=w.quickCreate({name:'Zahra Logistics',country:'Syria',contact:'y',phone:'+963 988 777 666'});
ok(weak.ok===true,'23.7 a weak or absent match does not block');

console.log('§24 quick create');
r=w.quickCreate({name:'Minimal Co',country:'Syria',contact:'Ali'});
ok(r.ok===false&&r.need.indexOf('phone or email')>-1,'24.2 neither phone nor email → refused, naming what is missing');
r=w.quickCreate({name:'Minimal Co',country:'Syria',contact:'Ali',email:'ali@minimal.sy'});
ok(r.ok===true&&r.id,'24.1 four fields are enough, and the id comes back immediately');
const nc=w.clientById(r.id);
ok(nc.status==='PROVISIONAL','24.3 saved as PROVISIONAL so the job proceeds in the same tick');
ok(nc.creditDays===0&&nc.creditLimit===0&&w.applyContract(nc.id).ok===false,'24.4 prepaid, zero credit, and no contract rate');
const task=w.itemById(r.task);
ok(!!task&&task.role==='sales'&&task.owner&&task.due,'24.5 a completion task exists with owner, next action and due date');
ok(Math.round((task.due-w.NOW())/D)===7,'24.5b …due in 7 days');
w.CLOCK+=8*D;w.sweep();
ok(w.escalation(task)===1,'24.6 it follows the same escalation ladder as everything else');
w.CLOCK=0;
const tray=w.provisionalTray();
ok(tray.length>0&&typeof tray[0].ageDays==='number','24.7 the provisional tray carries an age counter');
let cr=w.completeProfile(nc.id,{});
ok(cr.ok===false&&cr.need.length>0,'24.9 the profile cannot be completed while a mandatory field is empty');
cr=w.completeProfile(nc.id,{tax:'SY-12345',address:'Damascus'});
ok(cr.ok===true&&nc.status==='ACTIVE'&&w.itemById(r.task).status==='resolved','24.8 completing lifts it to ACTIVE and resolves the task');

console.log('§25 merging');
const dup=w.quickCreate({name:'TechLine Tradng',country:'Syria',contact:'Fadi',phone:'+963 944 000 999'},'typo entry, will merge');
const before=w.clientById('CL-001').contacts.length;
let mr=w.mergeClients(dup.id,'CL-001','');
ok(mr.ok===false,'25.4 a merge without a reason is refused');
mr=w.mergeClients(dup.id,'CL-001','same company, misspelled at intake');
ok(mr.ok===true&&w.clientById('CL-001').contacts.length>before,'25.1 contacts move to the survivor');
ok(w.clientById(dup.id).mergedInto==='CL-001'&&w.clientById(dup.id)!==null,'25.2 the merged record is kept, never deleted');
ok(w.resolveClient(dup.id).id==='CL-001','25.3 a lookup of the old id still resolves — to the survivor');
const b1=w.quickCreate({name:'Strict Terms Co',country:'Syria',contact:'q',phone:'+963 911 111 111',type:'business'});
w.clientById(b1.id).status='ACTIVE';w.setCredit(b1.id,30,4000);
const b2=w.quickCreate({name:'Prepaid Only Co',country:'Syria',contact:'z',phone:'+963 922 222 222',type:'business'});
w.clientById(b2.id).status='ACTIVE';
w.mergeClients(b1.id,b2.id,'same entity under two names');
ok(w.clientById(b2.id).creditDays===0,'25.5 the survivor keeps the STRICTER credit terms');
ok(/open shipments|شحنة مفتوحة/.test(w.T_w['open shipments will move with it']?'open shipments will move with it':''),'25.6 the open-shipment count is stated in the confirmation text');
ok(w.mergeClients('CL-001',dup.id,'reverse it').ok===false,'25.7 a circular merge is refused');

console.log('§26 credit — business only');
const ind=w.clientById('CL-003');
ok(w.setCredit(ind.id,30,1000).ok===false,'26.1 an individual can never be given credit days');
ok(w.setCredit('CL-001',30,5000).ok===true&&w.clientById('CL-001').creditDays===30,'26.2 a business may carry credit days and a limit');
const pb=w.quickCreate({name:'Fresh Business',country:'Syria',contact:'p',phone:'+963 977 777 777',type:'business'});
ok(w.setCredit(pb.id,30,1000).ok===false,'26.3 a provisional business stays prepaid until its profile is complete');
ok(w.outstanding('CL-001')===1800,'26.4 outstanding is derived from invoices, never typed');
ok(w.overdueAmount('CL-001')===1800,'26.4b …and the overdue slice with it');
const cc=w.checkCredit('CL-001',4000);
ok(cc.ok===false&&cc.over===800,'26.5 a booking beyond the limit warns and states by how much (800 over)');
ok(w.checkCredit('CL-003',9999).prepaid===true,'26.5b an individual is simply prepaid, with no limit logic');
w.setActor('U-02');
ok(w.releaseOverLimit('CL-001','urgent','ops').ok===false,'26.6 a non-manager cannot release over the limit');
w.setActor('U-00');
ok(w.releaseOverLimit('CL-001','','manager').ok===false,'26.6b …and the manager still needs a reason');
ok(w.releaseOverLimit('CL-001','director approved by phone, payment tomorrow','manager').ok===true&&w.RELEASE_OVERRIDES.length===1,'26.6c with a reason it is allowed and logged');

console.log('§27 standing rules');
w.go('s7');
ok(/Provisional|مؤقّت/.test(sh())&&/Quick create|إنشاء سريع/.test(sh()),'27.0 the board renders the tray and the quick create');
const warm=['creating a client is easy · creating a duplicate is hard','a client sitting provisional for a month is a business risk, not an admin detail','individuals are prepaid — credit is for business accounts only'];
ok(warm.filter(s=>!w.T_w[s]).length===0,'27.1 every warm string has an Arabic twin');
ok(/class="machine"/.test(sh()),'27.2 machine values LTR-isolated');
w.setLang('ar');
ok(/العملاء/.test(sh())&&/مؤقّت/.test(sh()),'27.1b AR renders');
w.setLang('en');
console.log('\n'+(f?('FAIL — '+f+' of '+n):('ALL PASS — '+n+' checks')));
process.exit(f?1:0);
