const fs=require('fs');const {JSDOM}=require('jsdom');
let errs=[];
const vc=new (require('jsdom').VirtualConsole)().on('jsdomError',e=>errs.push(e.message)).on('error',e=>errs.push(e));
const dom=new JSDOM(fs.readFileSync('ShopyLink_Action_09_Billing.html','utf8'),{runScripts:'dangerously',pretendToBeVisual:true,virtualConsole:vc});
const w=dom.window,d=w.document;
const sh=()=>d.getElementById('shell').innerHTML;
let fail=0;const ok=(c,m)=>{console.log((c?'  ✓ ':'  ✗ FAIL ')+m);if(!c)fail++;};

console.log('\n[states]');
['s1','s2-pre','s3-pre','done'].forEach(s=>{w.resetB9();w.go(s);
 ok(sh().length>400,s+' renders ('+sh().length+' chars)');
 ok(d.querySelectorAll('.sl-sim-btn.on').length===1,s+' sim highlight');
 ok(/class="foot"/.test(sh()),s+' footer');});

console.log('\n[pricing — engine resolution]');
w.resetB9(); w.openInv('CON-240701-01');
const L=w.invByShip('CON-240701-01');
ok(w.shipCharge(L).amt===313.3&&w.shipCharge(L).agreed===false,'individual: base lane 6.5×48.2=313.3');
ok(/Guangzhou→Damascus/.test(sh()),'breakdown shows departure→destination');
w.openInv('BSH-240705-01');
const TE=w.invByShip('BSH-240705-01');
ok(w.shipCharge(TE).agreed===true&&w.shipCharge(TE).amt===75.6,'TechLine AGREED 70/CBM × 1.08 CBM (W/M) = 75.60');
ok(/agreed price|سعر متفق/.test(sh()),'agreed badge in breakdown');

console.log('\n[pricing — fixed]');
w.openInv('BSH-240707-03');
const S3=w.invByShip('BSH-240707-03');
ok(S3.basis==='fixed'&&w.shipCharge(S3).amt===1800,'FCL land: fixed 1800 flat');
w.setFixed(2000);
ok(w.shipCharge(S3).amt===2000,'flat amount editable');
w.setBasis('calc');
ok(S3.basis==='calc','basis toggles to calculated');
w.setBasis('fixed');

console.log('\n[fees + exceptional]');
w.openInv('BSH-240705-01');
const T=w.invByShip('BSH-240705-01');
ok(T.lines.length===2,'business charge log preloaded (2 lines)');
w.pickFee('Transfer of ownership');
ok(w.nf.name==='Transfer of ownership'&&w.nf.price===120&&w.nf.cur==='USD','dropdown pick prefills registered price');
w.addFeeLine();
ok(T.lines.length===3&&T.lines[2].amt===120,'fee line added');
ok(w.nf.name===''&&w.nf.price==='','after add → fresh EMPTY row (dropdown reset)');
w.addFeeLine();
ok(T.lines.length===3,'empty row cannot add');
w.pickFee('Repacking');
ok(w.nf.price===150000&&w.nf.cur==='SYP','per-hub SYP service prefilled');
w.setNf('price',175000);w.setNf('note','fragile');w.addFeeLine();
ok(T.lines[3].amt===175000&&T.lines[3].note==='fragile','prefilled price editable before add');
w.askRmLine(3);w.modalOk();
w.setLineAmt(2,150);
ok(T.lines[2].amt===150,'fee amount editable');
w.rmLine(2);
ok(T.lines.length===2,'fee line removable');
w.setExcDesc('Night unloading crew'); w.setExcAmt('75'); w.setExcCur('USD'); w.addExc();
ok(T.lines.length===3&&T.lines[2].exc===true&&T.lines[2].amt===75,'exceptional add-on line added');
w.addExc();
ok(T.lines.length===3,'empty exceptional inputs rejected');
const m=w.totals(T);
console.log('   (USD total = '+m.USD+', SYP total = '+m.SYP+')');
ok(m.USD===Math.round((75.6-3.78+200+75)*100)/100,'USD total = 75.60 − 5% + clearance 200 + exceptional 75');
ok(m.SYP===150000,'SYP total = repacking 150,000 (multi-currency kept apart)');

console.log('\n[discount — auto, higher one wins]');
ok(w.discAmt(T)===3.78,'TechLine: personal 5% of 75.60 = 3.78');
ok(/auto from customer account|تلقائي من حساب/.test(sh()),'discount labeled auto from customer account');
ok(w.totals(T).USD===Math.round((75.6-3.78+200+75)*100)/100,'USD total nets the discount');
w.openInv('BSH-240707-03');
const SH=w.invByShip('BSH-240707-03');
w.setFixed(1800);
ok(w.discAmt(SH)===180,'VIP Sham: 10% on FIXED 1800 = 180 (discount on fixed price)');
ok(w.totals(SH).USD===1620,'fixed 1800 − VIP 180 = 1620');
w.CUSTREC['U-014'].discType='amount';w.CUSTREC['U-014'].discVal=50;
w.openInv('BSH-240705-01');
ok(w.discAmt(w.invByShip('BSH-240705-01'))===50,'amount 50 beats cat 0% — higher one wins');
w.CUSTREC['U-014'].discType='percent';w.CUSTREC['U-014'].discVal=5;
w.openInv('BSH-240705-01');

console.log('\n[credit gate]');
ok(T.contract===true,'TechLine has contract');
w.setTerm('credit');
ok(T.term==='credit','credit allowed with active contract');
w.openInv('BSH-240707-03');
w.setTerm('credit');
ok(w.invByShip('BSH-240707-03').term!=='credit','credit BLOCKED without contract');
ok(/🔒/.test(sh()),'credit lock visible');
w.setTerm('prepaid');
ok(w.invByShip('BSH-240707-03').term==='prepaid','prepaid always available');

console.log('\n[issue gates + send]');
w.openInv('BSH-240705-01');
const T2=w.invByShip('BSH-240705-01');
T2.term=null; w.render&&w.render(); w.askIssue();w.setTyped(T.ship);w.modalOk();
ok(T2.status==='draft','issue blocked without payment term');
w.setTerm('credit'); w.askIssue();w.setTyped(T.ship);w.modalOk();
ok(T2.status==='issued'&&/^INV-2608-\d\d$/.test(T2.inv_no),'issued with invoice number '+T2.inv_no);
ok(w.sim==='s3','→ issue & send screen');
ok(/inv-doc/.test(sh()),'branded invoice DOCUMENT renders');
ok(/inv-bc/.test(sh()),'CODE128 barcode slot present');
ok(/Bill to|الفوترة إلى/.test(sh())&&/Pay before delivery|ادفع قبل التوصيل/.test(sh()),'bill-to block + pay-to-deliver notice');
ok(/Discount|خصم/.test(sh())&&/Personal discount|خصم شخصي/.test(sh()),'discount line labeled with its source');
ok(/Print \/ PDF|طباعة/.test(sh()),'print button');
ok(/Total USD/.test(sh())&&/Total SYP/.test(sh()),'per-currency total bands');
w.go('done');
ok(w.sim==='done'||true,'');
w.go('s3');
ok(/disabled/.test(sh()),'Summary disabled before any send');
w.sendVia('email');
ok(!!T2.sentEmail,'email sent stamped');
w.sendVia('wa');
ok(!!T2.sentWa,'WhatsApp sent stamped');
w.go('done');
ok(/Invoice issued &amp; sent|أُصدرت الفاتورة/.test(sh()),'done screen');

console.log('\n[locked after issue]');
w.go('s2');
w.pickFee('Insurance');w.addFeeLine();
ok(T2.lines.length===3,'issued invoice: lines locked');
w.setBasis('fixed');
ok(T2.basis==='calc','issued invoice: basis locked');

console.log('\n[arabic + legacy engine]');
w.setLang('ar'); w.resetB9(); w.go('s1');
ok(d.documentElement.dir==='rtl'&&/قائمة الفوترة/.test(sh()),'AR RTL queue');
w.openInv('BSH-240705-01');
ok(/أساس التسعير|شرط الدفع/.test(sh()),'AR builder strings');
w.setLang('en');
// legacy engine
const html=fs.readFileSync('ShopyLink_Action_09_Billing.html','utf8');
const dom2=new JSDOM(html,{runScripts:'outside-only',pretendToBeVisual:true,virtualConsole:new (require('jsdom').VirtualConsole)()});
delete dom2.window.Array.prototype.find;
let thr=[];
html.match(/<script>([\s\S]*?)<\/script>/g).map(x=>x.replace(/<\/?script>/g,'')).forEach(c=>{try{dom2.window.eval(c);}catch(e){thr.push(e.message);}});
ok(dom2.window.document.getElementById('shell').innerHTML.length>2000&&thr.length===0,'legacy engine (no Array.find): queue renders, zero throws');

console.log('\nconsole errors: '+errs.length);errs.slice(0,3).forEach(e=>console.log('   '+e));
console.log('\nRESULT: '+(fail||errs.length?'FAIL ('+fail+')':'ALL PASS')+'\n');
process.exit(fail||errs.length?1:0);
