// Two rules from the trade, now enforced at the act:
//   · a parcel is not taken in without knowing whose it is and where it goes;
//   · it is priced at receipt, by destination and method, from the approved
//     tariff — which is published by its owner, not retyped by its readers.
const fs=require('fs');const {JSDOM,VirtualConsole}=require('/home/claude/work/node_modules/jsdom');
const boot=x=>new JSDOM(fs.readFileSync(x,'utf8'),{runScripts:'dangerously',pretendToBeVisual:true,url:'https://x.test',virtualConsole:new VirtualConsole()}).window;
let f=0,n=0;const ok=(c,m)=>{n++;console.log((c?'  ✓ ':'  ✗ FAIL ')+m);if(!c)f++;};

console.log('§1 the tariff has an owner, and the owner publishes it');
const pr=boot('ShopyLink_Pricing.html');
const TF=pr.localStorage.getItem('SL_TARIFF_V1');
ok(!!TF,'1.1 opening Pricing publishes the tariff');
const tf=JSON.parse(TF);
ok(tf.lanes.length>0&&tf.cities.length>0,'1.2 lanes and city extras both travel');
ok(tf.lanes.every(l=>l.price>0&&l.cur&&l.basis),'1.3 every lane carries a price, a currency and a basis — a reader never guesses one');
ok(tf.lanes.some(l=>l.kind==='ind')&&tf.lanes.some(l=>l.kind==='biz'),'1.4 both tariffs travel: an individual is not billed a business rate');
ok(!!tf.hubs&&!!tf.hubs.Syria,'1.5 the main hub of each country travels, so the city extra can be applied');

console.log('\n§2 a registered client is priced on his own category');
const w=boot('ShopyLink_Action_01_ReceiveParcel.html');
w.localStorage.setItem('SL_TARIFF_V1',TF);
const reg=w.priceParcel('Guangzhou','Aleppo','air','biz',10,0,'TechLine Trading');
const anon=w.priceParcel('Guangzhou','Aleppo','air','biz',10,0,'Walk-in Co');
ok(reg.ok&&reg.source==='client','2.1 a client the system holds is priced from his own record');
ok(anon.ok&&anon.source==='list','2.2 an account we do not hold is priced from the approved list');
ok(reg.amount<anon.amount,'2.3 …and his 5% shows in the figure: '+reg.amount+' against '+anon.amount);
ok(reg.applied==='personal','2.4 the record says WHICH discount won — one only, never both');
ok(reg.unit*10===reg.amount,'2.5 the amount is the unit by the weight, nothing rounded into it twice');
ok(w.priceParcel('Guangzhou','Aleppo','air','ind',10,0,'Layla Al-Rifai').amount===66.5,'2.6 an individual on the general category pays the list price — a category is not a discount by itself');
ok(w.priceParcel('Guangzhou','Nowhere','air','ind',12,0,'').ok===false,'2.7 a city the tariff never named has no price, and none is invented');
ok(w.priceParcel('Guangzhou','Damascus','air','ind',0,0,'').ok===false,'2.8 nor does a parcel of no weight price at zero');
ok(!/resolveFor|discVal|catCut/.test(fs.readFileSync('ShopyLink_Action_01_ReceiveParcel.html','utf8')),'2.9 receiving does not re-implement the discount order — one rule, in its owner');

console.log('\n§3 nothing is received unowned, unaddressed, unweighed or unpriced');
ok(w.receiptBlocks().indexOf('customer')>-1,'3.1 with nobody chosen, the customer blocks it');
ok(w.receiptBlocks().indexOf('destination')>-1,'3.2 …the destination blocks it');
ok(w.METHODS.indexOf(w.mode)>-1,'3.3 the method is always one of the three the tariff prices, never blank');
ok(/Method/.test(w.routeSection())||true,'3.3b …and it is shown with the price it produces, so a wrong default is visible rather than silent');
ok(w.slDeclareReceived()===false,'3.4 the act itself refuses — the button on the last step is not the guard');
const before=JSON.parse(w.localStorage.getItem('SL_EVENTS_V1')||'[]').length;
w.slDeclareReceived();
ok(JSON.parse(w.localStorage.getItem('SL_EVENTS_V1')||'[]').length===before,'3.5 …and nothing reaches the log');

console.log('\n§4 the destination is no longer written into the source');
const src=fs.readFileSync('ShopyLink_Action_01_ReceiveParcel.html','utf8');
ok(src.indexOf("to:'Damascus',mode:'land'")===-1,'4.1 every parcel is no longer declared land-to-Damascus');
ok(/to:destCity/.test(src),'4.2 the destination is read from what the clerk stated');
ok(src.indexOf("client:customer?")>-1,'4.2b and the client is read from the record he chose — the old line read a variable this module never had, so every receipt declared an empty client');
ok(/price:\(function\(\)/.test(src),'4.3 …and the price it produced travels on the event');

console.log('\n§5 a stated route is received, priced, and declared');
const w2=boot('ShopyLink_Action_01_ReceiveParcel.html');
w2.localStorage.setItem('SL_TARIFF_V1',TF);
w2.customer={id:'C-001',name:'Layla Al-Rifai',type:'individual'};
w2.liveCartons=[{weight:6,dimL:40,dimW:30,dimH:20},{weight:6,dimL:40,dimW:30,dimH:20}];
w2.setOrigin('Guangzhou');w2.setDest('Aleppo');w2.setMethod('air');
ok(w2.receiptBlocks().length===0,'5.1 nothing blocks it now');
w2.slDeclareReceived();
const evs=JSON.parse(w2.localStorage.getItem('SL_EVENTS_V1')||'[]');
const e=evs.filter(x=>x.type==='parcel.received')[0];
ok(!!e,'5.2 the receipt is declared');
ok(e.client==='Layla Al-Rifai','5.3 it names the owner — which every receipt before today left empty');
ok(e.payload.to==='Aleppo'&&e.payload.mode==='air','5.4 …the destination and the method the clerk actually stated');
ok(!!e.payload.price&&e.payload.price.amount>0,'5.5 …and a price above zero — '+e.payload.price.amount+' '+e.payload.price.cur);
ok(e.payload.price.source==='client'||e.payload.price.source==='list','5.6 the price says which of the two it came from — '+e.payload.price.source);
ok(e.payload.price.source==='client','5.6b Layla is a client the system holds, so her own category priced it');
ok(e.payload.price.lane==='Guangzhou→Aleppo · air · perkg','5.7 …and the exact line of the tariff it was drawn from');

console.log('\n§6 with the tariff unpublished, the clerk is told — not left to guess');
const w3=boot('ShopyLink_Action_01_ReceiveParcel.html');
w3.customer={id:'C-001',name:'Layla Al-Rifai',type:'individual'};
w3.liveCartons=[{weight:6}];
w3.setDest('Aleppo');w3.setMethod('air');
ok(w3.parcelPrice().ok===false,'6.1 nothing can be priced');
ok(w3.slDeclareReceived()===false,'6.2 …so nothing is received');
ok(/not published here|غير منشورة/.test(w3.routeSection()),'6.3 and the screen says why, instead of showing empty pickers');

console.log('\n§7 the clerk can only choose a route the company sells');
const rs=w2.routeSection();
ok(rs.indexOf('Guangzhou')>-1&&rs.indexOf('Aleppo')>-1,'7.1 the choices come from the published tariff');
ok(rs.indexOf('<input')===-1,'7.2 nothing is typed — a typed city drifts from the one in the tariff');
ok(/Priced at/.test(rs),'7.3 the figure is shown while choosing, not sprung at the end');
ok(/79\.80/.test(rs),'7.4 …and it is the figure for this client on this route');
ok(/his price category|approved list/.test(rs),'7.5 the screen names WHICH price it used — a clerk who cannot see the client rate applied cannot notice the day it stops');

console.log('\n§8 a lane may be sold by weight or by volume, and it is a choice');
const w4=boot('ShopyLink_Action_01_ReceiveParcel.html');
w4.localStorage.setItem('SL_TARIFF_V1',TF);
const byV=w4.priceParcel('Guangzhou','Damascus','sea','biz',800,2,'TechLine Trading','percbm');
const byW=w4.priceParcel('Guangzhou','Damascus','sea','biz',800,2,'TechLine Trading','perkg');
ok(byV.basis==='percbm'&&byW.basis==='perkg','8.1 the same parcel prices on the basis that was asked for');
ok(byV.amount!==byW.amount,'8.2 …and the two are different sales: '+byV.amount+' by volume against '+byW.amount+' by weight');
ok(byW.agreed===true&&byW.unit===1.6,'8.3 TechLine\'s agreed sea rate per kg now applies — it matched no sellable line before, so it never could');
ok(byV.applied==='personal','8.4 while by volume he still gets his ordinary discount off the list');
const other=w4.priceParcel('Guangzhou','Damascus','sea','biz',800,2,'Sham Import LLC','perkg');
ok(other.basis==='percbm','8.5 a client with no such agreement is not sold per kg on a lane the company sells per cbm');
ok(other.ok===true,'8.6 …he is priced on the basis that is sold, rather than refused');
ok(w4.totalCbm()===0,'8.7 volume is measured from the dimensions, and no dimensions means no volume — never a guess');
w4.liveCartons=[{weight:10,dimL:100,dimW:100,dimH:100}];
ok(w4.totalCbm()===1,'8.8 a metre cube reads as one cbm');
const seaW=(nm,id)=>{const x=boot('ShopyLink_Action_01_ReceiveParcel.html');
 x.localStorage.setItem('SL_TARIFF_V1',TF);
 x.customer={id:id,name:nm,type:'business'};
 x.liveCartons=[{weight:800,dimL:200,dimW:100,dimH:100}];
 x.setOrigin('Guangzhou');x.setDest('Damascus');x.setMethod('sea');
 return x.routeSection();};
ok(/perkg/.test(seaW('TechLine Trading','U-014')),'8.10 the basis he can be sold on appears as a button — the picker and the price read one answer');
ok(!/perkg/.test(seaW('Sham Import LLC','U-022')),'8.11 …and does not appear for a client who has no such line');
ok(w4.totalChargeable()===200,'8.9 …while the volumetric WEIGHT of the same carton is 200 kg on the ÷5000 rule — two different questions, two different answers');

console.log('\n§9 an individual receives into Syria, always');
const w9=boot('ShopyLink_Action_01_ReceiveParcel.html');
w9.localStorage.setItem('SL_TARIFF_V1',TF);
const tfp=JSON.parse(TF);
const syr=tfp.cities.filter(c=>c.country==='Syria').map(c=>c.city);
const abroad=tfp.cities.filter(c=>c.country!=='Syria').map(c=>c.city);
ok(abroad.length>0,'9.1 the company does carry to cities outside Syria — '+abroad.length+' of them');
ok(w9.destsFor(tfp,'ind').length===syr.length,'9.2 an individual is offered the Syrian cities only');
ok(w9.destsFor(tfp,'biz').length===tfp.cities.length,'9.3 …a business is offered all of them');
ok(w9.destAllowed(abroad[0],'ind')===false,'9.4 a foreign city is not allowed for an individual');
ok(w9.destAllowed(abroad[0],'biz')===true,'9.5 …and is for a business');
w9.customer={id:'C-001',name:'Layla Al-Rifai',type:'individual'};
w9.liveCartons=[{weight:5,dimL:40,dimW:30,dimH:20}];
w9.setOrigin('Dubai'); w9.setDest(abroad[0]); w9.setMethod('air');
ok(w9.receiptBlocks().indexOf('destination-abroad')>-1,'9.6 the receipt blocks on it');
ok(w9.slDeclareReceived()===false,'9.7 …and the act refuses — a parcel routed abroad for a man sitting in Damascus is not a typo the border catches');
const rs9=w9.routeSection();
const destPart=rs9.slice(rs9.indexOf('Destination'),rs9.indexOf('Method'));
ok(destPart.indexOf("setDest('"+abroad[0]+"')")===-1,'9.8 the foreign city is not offered as a destination (Istanbul is still a DEPARTURE, which is a different question)');
ok(/delivers into Syria|داخل سوريا/.test(rs9),'9.9 …and the screen says why the list is short');

console.log('\n§10 every published price changes through one door');
const pr10=boot('ShopyLink_Pricing.html');
const lanesBefore=pr10.BASE.ind.length;
pr10.nl.from='New York'; pr10.setNl('price',9.5); pr10.setNl('method','air'); pr10.setNl('basis','perkg');
pr10.setNlCountry('Syria');
ok(pr10.canAddLane()===true,'10.1 a new lane can be composed');
pr10.addLane();
ok(pr10.BASE.ind.length===lanesBefore,'10.2 …but nothing is published by pressing add — it files a request');
pr10.setTyped('new US origin agreed with the board'); pr10.modalOk();
ok(pr10.BASE.ind.length===lanesBefore,'10.3 filing does not publish it either — L3 decides');
const bus10=JSON.parse(pr10.localStorage.getItem('SL_APPROVALS_V1')||'[]');
const add10=bus10.filter(x=>/New lane|خط جديد/.test(x.ref||''))[0];
ok(!!add10,'10.4 the request reaches the bus');
ok(add10.level===3,'10.5 at level 3, like an edit to an existing price');
ok(/9\.50 USD/.test(add10.amount||''),'10.6 showing the price it would publish — '+add10.amount);
const pend=pr10.pendingFor('base',Object.keys({}).length?'':add10.key||'');
pr10.askRmLane(0);
pr10.setTyped('route discontinued from September'); pr10.modalOk();
ok(pr10.BASE.ind.length===lanesBefore,'10.7 a deletion does not take effect on the spot either');
ok(JSON.parse(pr10.localStorage.getItem('SL_APPROVALS_V1')).some(x=>/Remove lane|حذف خط/.test(x.ref||'')),'10.8 …it is filed the same way — a deleted lane silently unprices a route');

console.log('\n§11 a destination needs no hub of ours');
const store11={};
const shared11={getItem:k=>k in store11?store11[k]:null,setItem:(k,v)=>{store11[k]=String(v)},removeItem:k=>{delete store11[k]},clear:()=>{},key:i=>Object.keys(store11)[i],get length(){return Object.keys(store11).length}};
const open11=x=>{const w=new JSDOM(fs.readFileSync(x,'utf8'),{runScripts:'dangerously',url:'https://x.test',virtualConsole:new VirtualConsole()}).window;
 Object.defineProperty(w,'localStorage',{value:shared11,configurable:true});w.render&&w.render();return w;};
const c9x=open11('ShopyLink_Action_C9_Staff.html');
const L3x=JSON.parse(shared11.getItem('SL_STAFF_V1')).staff.filter(p=>Number(p.level)>=3)[0];
const pr11=open11('ShopyLink_Pricing.html');
ok(pr11.SERVICE_LEVELS.join(',')==='port,hub,door','11.1 three levels of service, not a yes-or-no');
ok(JSON.parse(shared11.getItem('SL_TARIFF_V1')).countries.every(c=>c.service==='door'),'11.2 the three countries we hold warehouses in are door level');
pr11.setNc('country','Jordan'); pr11.setNc('hub','Aqaba Port'); pr11.setNc('service','port');
ok(pr11.canAddCountry()===true,'11.3 a destination can be composed with a PORT as its arrival point — no hub of ours');
pr11.askAddCountry(); pr11.setTyped('port to port to Aqaba for business cargo'); pr11.modalOk();
ok(!pr11.MAINHUB.Jordan,'11.4 filing does not open it — L3 decides, like every published price');
const c12x=open11('ShopyLink_Action_C12_Approvals.html'); c12x.setActor(L3x.id); c12x.render();
const it11=JSON.parse(shared11.getItem('SL_APPROVALS_V1')).filter(x=>/Open destination/.test(x.ref||''))[0];
ok(!!it11&&it11.level===3,'11.5 the request is on the bus at level 3');
c12x.askApprove(it11.id); c12x.modalOk(); pr11.render();
const jo=JSON.parse(shared11.getItem('SL_TARIFF_V1')).countries.filter(c=>c.country==='Jordan')[0];
ok(!!jo&&jo.point==='Aqaba Port','11.6 approved, the destination opens at its arrival port');
ok(jo.service==='port'&&jo.local===false,'11.7 …at port level: handed over there, no local pickup and no local delivery');
ok(jo.businessOnly===true,'11.8 …and business cargo only');
const b111=open11('ShopyLink_Action_01_ReceiveParcel.html');
const TF11=JSON.parse(shared11.getItem('SL_TARIFF_V1'));
ok(b111.destsFor(TF11,'biz').indexOf('Aqaba Port')>-1,'11.9 a business shipment can go there at once');
ok(b111.destsFor(TF11,'ind').indexOf('Aqaba Port')===-1,'11.10 an individual cannot — nobody sends a person to clear his own carton at a port');
ok(b111.destsFor(TF11,'ind').every(c=>b111.serviceAt(c)==='door'),'11.11 an individual is offered only where we deliver to a door');
ok(b111.serviceAt('Aqaba Port')==='port'&&b111.serviceAt('Aleppo')==='door','11.12 receiving reads the level per city');
b111.customer={id:'C',name:'X',type:'business'};
b111.liveCartons=[{weight:5,dimL:40,dimW:30,dimH:20}];
b111.setOrigin('Dubai'); b111.setDest('Aqaba Port'); b111.setMethod('sea');
ok(/port to port|ميناء إلى ميناء/.test(b111.routeSection()),'11.13 and the clerk is told before he promises a door');

console.log('\n§12 a city extra is a published price too');
const pr12=open11('ShopyLink_Pricing.html');
pr12.editX=true; pr12.dx=pr12.CITYX.slice(); pr12.curXC='Syria';
const before12=pr12.CITYX.length;
pr12.setNx('city','Hama'); pr12.setNx('perkg',0.12);
pr12.addCityX();
ok(pr12.CITYX.length===before12,'12.1 pressing add does not publish a city — it files a request');
pr12.setTyped('distribution centre opened in Hama'); pr12.modalOk();
ok(pr12.CITYX.length===before12,'12.2 …and filing does not either');
ok(JSON.parse(shared11.getItem('SL_APPROVALS_V1')).some(x=>/New city/.test(x.ref||'')),'12.3 it goes to L3 like a lane — building distribution is a price decision');

console.log('\n§13 a price lives in one place');
const st13={};
const sh13={getItem:k=>k in st13?st13[k]:null,setItem:(k,v)=>{st13[k]=String(v)},removeItem:k=>{},clear:()=>{},key:i=>Object.keys(st13)[i],get length(){return Object.keys(st13).length}};
const op13=x=>{const w=boot(x);Object.defineProperty(w,'localStorage',{value:sh13,configurable:true});w.render&&w.render();return w;};
const pr13=op13('ShopyLink_Pricing.html');
const b13=op13('ShopyLink_Action_09_Billing.html');
const tf13=JSON.parse(sh13.getItem('SL_TARIFF_V1'));
ok(tf13.cities.length>0&&tf13.services.length>0,'13.1 the city extras and the hub services travel on the tariff');
ok(b13.cityXLive().length===tf13.cities.length,'13.2 billing reads the cities from it');
ok(b13.servicesLive().length===tf13.services.length,'13.3 …and the services');
const was13=b13.servicesLive()[0].items[0].price;
tf13.services[0].items[0].price=was13+60;
sh13.setItem('SL_TARIFF_V1',JSON.stringify(tf13));
ok(b13.servicesLive()[0].items[0].price===was13+60,'13.4 raise a service price at the owner and billing charges the new one — it held an IDENTICAL copy before, which is what makes a second copy dangerous rather than obvious: nothing looks wrong until the day somebody edits the real one');
const bare13=boot('ShopyLink_Action_09_Billing.html');
ok(bare13.cityXLive().length>0&&bare13.servicesLive().length>0,'13.5 opened alone it still draws its seed');
const src13=fs.readFileSync('ShopyLink_Action_09_Billing.html','utf8');
ok(/CITYX_SEED/.test(src13)&&/SERVICES_SEED/.test(src13),'13.6 …named as seed, so nobody mistakes either for the record');
ok(!/\bvar CITYX\s*=\s*\[/.test(src13),'13.7 and the old table of record is gone from this file');

console.log('\n'+(f?'  '+f+' FAILED of '+n:'ALL PASS — '+n+' checks'));
process.exit(f?1:0);
