const fs=require('fs');const {JSDOM,VirtualConsole}=require('/home/claude/work/node_modules/jsdom');
const dom=new JSDOM(fs.readFileSync('ShopyLink_D1_Control.html','utf8'),{runScripts:'dangerously',pretendToBeVisual:true,virtualConsole:new VirtualConsole()});
const w=dom.window,d=w.document;const sh=()=>d.getElementById('shell').innerHTML;
let f=0,n=0;const ok=(c,m)=>{n++;console.log((c?'  ✓ ':'  ✗ FAIL ')+m);if(!c)f++;};
const T='TRP-8842';
const sum=(parts)=>Math.round(parts.reduce((a,p)=>a+p.amount,0)*100)/100;

console.log('§18 booking a cost');
const c=w.bookCost(T,{code:'storage',amount:60,supplier:'CFS',key:'cbm'});
ok(!!c&&c.ref&&c.amount===60,'18.1 a cost is booked once against the trip');
ok(!!w.duplicateOf(T,{code:'storage',amount:60,supplier:'CFS'}),'18.2 an identical cost is detectable as a possible duplicate');
ok(!!c.by&&!!c.at,'18.3 who booked it and when are recorded');
ok(w.voidCost(T,c.ref,'')===false,'18.4 voiding needs a reason');
ok(w.voidCost(T,c.ref,'booked on the wrong trip')===true,'18.4b …then it is voided');
ok(w.tripById(T).costs.some(x=>x.ref===c.ref&&x.void)&&w.liveCosts(T).every(x=>x.ref!==c.ref),'18.4c it stays in the record but leaves every total');
const dir=w.liveCosts(T).filter(x=>x.ship==='SL-9603')[0];
const dr=w.allocate(T,dir);
ok(dr.ok&&dr.parts.length===1&&dr.parts[0].ship==='SL-9603'&&dr.parts[0].amount===120,'18.5 a direct cost goes wholly to its shipment');

console.log('§19 the keys');
ok(w.KEYS.join(',')==='cbm,weight,pieces,manual','19.1 four keys: cbm, weight, pieces, manual');
const truck=w.liveCosts(T).filter(x=>x.code==='truck')[0];
let r=w.allocate(T,truck);
ok(r.parts.find(p=>p.ship==='SL-9601').amount===360&&r.parts.find(p=>p.ship==='SL-9603').amount===900,'19.2 by CBM: 2/3/5 of 1800 → 360 / 540 / 900');
w.setKey(T,truck.ref,'weight');
r=w.allocate(T,truck);
ok(r.parts.find(p=>p.ship==='SL-9602').amount>r.parts.find(p=>p.ship==='SL-9603').amount,'19.3 by weight the heavy shipment pays more, not the bulky one');
ok(sum(r.parts)===1800,'19.4 the parts sum exactly to the cost');
w.setKey(T,truck.ref,'cbm');
const odd=w.bookCost(T,{code:'cfs',amount:100,supplier:'x',key:'pieces'});
w.setFact('SL-9601',{cbm:2,weight:900,pieces:1,revenue:520});
w.setFact('SL-9602',{cbm:3,weight:1500,pieces:1,revenue:700});
w.setFact('SL-9603',{cbm:5,weight:600,pieces:1,revenue:940});
const rr=w.allocate(T,odd);
ok(sum(rr.parts)===100,'19.5 100 ÷ 3 still sums to exactly 100.00 — no cent created or lost');
const again=w.allocate(T,odd);
ok(JSON.stringify(rr.parts)===JSON.stringify(again.parts),'19.5b …and the same shipment carries the odd cent every time');
w.setFact('SL-9601',{cbm:2,weight:900,pieces:8,revenue:520});
w.setFact('SL-9602',{cbm:3,weight:1500,pieces:12,revenue:700});
w.setFact('SL-9603',{cbm:5,weight:600,pieces:30,revenue:940});
w.voidCost(T,odd.ref,'test only');
const man=w.bookCost(T,{code:'inland',amount:300,supplier:'x',key:'manual',manual:{'SL-9601':50,'SL-9602':40}});
const mr=w.allocate(T,man);
ok(mr.ok===false&&/must total 100/.test(mr.why),'19.6 a manual split of 90% is refused, with the shortfall named');
man.manual={'SL-9601':50,'SL-9602':40,'SL-9603':10};
ok(w.allocate(T,man).ok===true&&sum(w.allocate(T,man).parts)===300,'19.6b at 100% it is accepted and sums exactly');
w.voidCost(T,man.ref,'test only');
const zero=w.bookCost('TRP-8830',{code:'cfs',amount:50,supplier:'x',key:'pieces'});
w.setFact('SL-9701',{cbm:1.08,weight:120,pieces:0,revenue:210});
const zr=w.allocate('TRP-8830',zero);
ok(zr.ok===true&&zr.parts[0].amount===50,'19.8 a single-shipment trip takes the whole cost whatever the key');
w.addShip('TRP-8830','SL-9702','Second client');
w.setFact('SL-9702',{cbm:0,weight:0,pieces:0,revenue:0});
const zr2=w.allocate('TRP-8830',zero);
ok(zr2.ok===false&&/no pieces/.test(zr2.why)&&zr2.zero.length===2,'19.7 with no data the key refuses and names the shipments, instead of dividing equally');
w.rmShip('TRP-8830','SL-9702');
w.voidCost('TRP-8830',zero.ref,'test only');
w.setFact('SL-9701',{cbm:1.08,weight:120,pieces:4,revenue:210});

console.log('§20 profit per shipment');
ok(w.revenue('SL-9601')===520,'20.1 revenue comes from the shipment itself');
ok(w.costOf('SL-9603',T)===900+90+120,'20.2 cost = allocated share + its own direct cost');
ok(w.profitOf('SL-9603',T)===940-1110,'20.3 a loss-making shipment reports a negative profit, unhidden');
const tp=w.tripById(T);
const sumShips=Math.round(tp.ships.reduce((a,s)=>a+w.profitOf(s.id,T),0)*100)/100;
ok(w.tripProfit(T)===sumShips,'20.4 the trip profit equals the sum of its shipments — no orphan money');
const bad=w.bookCost(T,{code:'storage',amount:70,supplier:'y',key:'manual',manual:{'SL-9601':20}});
ok(w.unallocated(T).length===1,'20.5 an unallocatable cost is visible as unallocated, never absorbed');
w.voidCost(T,bad.ref,'test only');
const p1=w.profitOf('SL-9601',T);
const brd=w.liveCosts(T).filter(x=>x.code==='border')[0];
w.voidCost(T,brd.ref,'charged to the wrong trip');
ok(w.profitOf('SL-9601',T)>p1,'20.6 voiding a cost re-computes every profit in the same tick');
ok(w.thinMargin('SL-9603',T)===true,'20.7 a margin below 10% is flagged');

console.log('§21 honesty');
w.go('s6');
ok(/allocated|وُزِّعت/.test(sh())&&/by CBM|بالمتر المكعب/.test(sh()),'21.1 the key used is shown, not implied');
const before=w.AUDIT.length;
w.setKey(T,truck.ref,'weight');
ok(w.historyOf(T).some(e=>/cbm → weight/.test(e.what)),'21.2 changing the key logs both names');
w.setKey(T,truck.ref,'cbm');
ok(w.costSourceFor('SL-9601',T).length>0&&w.costSourceFor('SL-9601',T)[0].ref,'21.4 every share traces back to the cost line that produced it');

console.log('§22 standing rules');
const warm=['a cost is booked once at trip level and split across the shipments that caused it','the parts always sum to the cost, to the cent · profit per client is calculated, never guessed','It is never deleted — it stays in the record, marked void, and every profit re-computes.'];
ok(warm.filter(s=>!w.T_w[s]).length===0,'22.1 every warm string has an Arabic twin');
ok(/class="machine"/.test(sh()),'22.2 machine values LTR-isolated');
w.setLang('ar');
ok(/توزيع الكلفة/.test(sh())&&/الربح لكل شحنة/.test(sh()),'22.1b AR renders');
w.setLang('en');
console.log('\n'+(f?('FAIL — '+f+' of '+n):('ALL PASS — '+n+' checks')));
process.exit(f?1:0);
