const fs=require('fs');const {JSDOM,VirtualConsole}=require('/home/claude/work/node_modules/jsdom');
const dom=new JSDOM(fs.readFileSync('ShopyLink_D1_Control.html','utf8'),{runScripts:'dangerously',pretendToBeVisual:true,virtualConsole:new VirtualConsole()});
const w=dom.window,d=w.document;const sh=()=>d.getElementById('shell').innerHTML;
let f=0,n=0;const ok=(c,m)=>{n++;console.log((c?'  ✓ ':'  ✗ FAIL ')+m);if(!c)f++;};
const D=w.DAY,H=w.HOUR,T0=w.T0;

console.log('§9 lifetime');
const s1=w.shipById('BSH-240520-01');
ok(w.lifetime(s1)===44*D,'9.1 measured from B1 receipt (52d ago) to POD (8d ago) = 44d, not from booking');
const a=w.lifetime(s1); w.CLOCK+=10*D; const b=w.lifetime(s1); w.CLOCK-=10*D;
ok(a===b,'9.2 a delivered shipment is frozen — later reads are identical');
const run=w.shipById('BSH-240705-01');
const before=w.lifetime(run);
w.touch(w.all()[0].id); w.handover(w.all()[2].id,'wh'); w.reassign(w.all()[1].id,'U-02','test');
ok(w.lifetime(run)===before,'9.3 touching, handing over and reassigning do NOT reset it');
w.CLOCK+=2*D;
ok(w.lifetime(run)>before,'9.4 an undelivered shipment keeps running');
w.CLOCK-=2*D;
ok(Object.keys(s1.stamps).length>=6,'9.5 milestones are stamped, so the question is WHERE the time went');
ok(w.slicesSum(s1)===w.lifetime(s1),'9.6 the slices sum exactly to the total — no gap, no overlap');
ok(w.slicesSum(run)===w.lifetime(run),'9.6b …for a running shipment too');

console.log('§10 client-caused delay');
const c1=w.shipById('CON-240610-03');
ok(w.clientWait(c1)===2*D,'10.0 a 2-day client wait is measured');
ok(w.lifetime(c1)===5*D,'10.1 the total keeps running through it (5d)');
ok(w.controlled(c1)===w.lifetime(c1)-w.clientWait(c1),'10.2 controlled = total − client wait');
const probe=w.mkShip({id:'X-1',cust:'T',from:'Dubai',to:'Damascus',mode:'air',receivedAt:T0-10*D,stamps:{received:T0-10*D}});
w.startWait('X-1','a',T0-8*D); w.closeWait('X-1',T0-5*D);
w.startWait('X-1','b',T0-7*D); w.closeWait('X-1',T0-6*D);      // fully inside the first
ok(w.clientWait(probe)===3*D,'10.3 overlapping waits are counted once (union, not sum)');
w.startWait('X-1','open one',T0-2*D);
const live1=w.clientWait(probe); w.CLOCK+=1*D; const live2=w.clientWait(probe);
ok(live2>live1,'10.4 an open wait accrues live');
w.closeWait('X-1'); const frozen=w.clientWait(probe); w.CLOCK+=3*D;
ok(w.clientWait(probe)===frozen,'10.4b …and freezes when closed');
w.CLOCK=0;
const probe2=w.mkShip({id:'X-2',cust:'T',from:'Dubai',to:'Damascus',mode:'air',receivedAt:T0-2*D,stamps:{received:T0-2*D}});
w.startWait('X-2','way too long',T0-30*D);
ok(w.clientWait(probe2)<=w.lifetime(probe2),'10.6 client wait can never exceed the total');
w.go('s4');
ok(/total, as the client felt it|الإجمالي كما شعر/.test(sh())&&/under our control|تحت سيطرتنا/.test(sh()),'10.5 both figures are shown together and labelled');

console.log('§11 the promise');
ok(w.promiseFor('Guangzhou','Damascus','sea')===45*D,'11.1 promise registered per lane × mode');
ok(w.promiseFor('Istanbul','Aleppo','land')===null,'11.2 an unpromised lane returns null, never a default');
ok(/unpromised|بلا وعد/.test(sh()),'11.2b …and the board says so');
const pc=w.controlled(s1)/w.promiseOf(s1);
ok(Math.abs(w.promisePct(s1)-pc)<1e-9,'11.3 performance is judged on CONTROLLED time');
const mk=(ctl)=>{const s=w.mkShip({id:'P-'+ctl,cust:'T',from:'Guangzhou',to:'Damascus',mode:'sea',receivedAt:T0-ctl*D,stamps:{received:T0-ctl*D,delivered:T0}});s.podAt=T0;return s;};
ok(w.promiseTone(mk(40))==='green','11.4 89% of the promise → green (40/45)');
ok(w.promiseTone(mk(41))==='amber','11.4b 91% → amber');
ok(w.promiseTone(mk(45))==='amber','11.4c exactly 100% → amber, not red');
ok(w.promiseTone(mk(46))==='red','11.4d beyond the promise → red');
ok(w.onTime(mk(45))===true&&w.onTime(mk(46))===false,'11.3b on-time is decided at the promise line');
const ws=w.worstSlice(s1);
ok(!!ws&&ws.ms>0,'11.5 a breach names the stage that consumed the most time');
const av=w.avgLane('Guangzhou','Damascus','sea');
const openOne=w.SHIPS.filter(x=>!w.isDelivered(x)&&x.from==='Guangzhou'&&x.to==='Damascus'&&x.mode==='sea')[0];
ok(!!openOne&&av.n===w.deliveredIn('Guangzhou','Damascus','sea').length,'11.6 averages count delivered shipments only');
const sg=w.suggestPromise('Guangzhou','Damascus','sea');
ok(sg&&sg.days>0&&sg.n===av.n,'11.7 the suggested promise is the observed controlled average with its sample size');
const thin=w.suggestPromise('Istanbul','Damascus','land');
ok(thin&&thin.n<5&&thin.thin===true,'11.8 a promise on fewer than 5 samples is flagged thin');
ok(/thin|رقيقة/.test(sh()),'11.8b …and the board labels it');

console.log('§8 standing rules');
const warm=['total, as the client felt it','under our control','receipt to POD — nothing internal resets this clock','a promise built on fewer than 5 deliveries is marked thin — it is an indication, not a fact'];
ok(warm.filter(s=>!w.T_w[s]).length===0,'8.1 every new warm string has an Arabic twin');
w.setLang('ar');
ok(/سرعة التسليم/.test(sh())&&/تحت سيطرتنا/.test(sh()),'8.1b AR renders');
ok(/class="machine"/.test(sh()),'8.2 machine values LTR-isolated');
w.setLang('en');
console.log('\n'+(f?('FAIL — '+f+' of '+n):('ALL PASS — '+n+' checks')));
process.exit(f?1:0);
