const fs=require('fs');const {JSDOM,VirtualConsole}=require('/home/claude/work/node_modules/jsdom');
const dom=new JSDOM(fs.readFileSync('ShopyLink_D1_Control.html','utf8'),{runScripts:'dangerously',pretendToBeVisual:true,virtualConsole:new VirtualConsole()});
const w=dom.window,d=w.document;const sh=()=>d.getElementById('shell').innerHTML;
let f=0,n=0;const ok=(c,m)=>{n++;console.log((c?'  ✓ ':'  ✗ FAIL ')+m);if(!c)f++;};
const D=w.DAY;

console.log('§43 no number without context, and every number opens its list');
w.go('s1');
ok(/open the list|افتح القائمة/.test(sh()),'43.1 every figure invites the drill-down');
ok(/vs last week|nothing overdue|same as last week/.test(sh()),'43.2 each figure carries a comparison or a state, never a bare count');
const setOd=w.drillSet('overdue'), q=w.queueFor(w.ME.role);
ok(setOd.length===q.filter(x=>w.overdue(x)).length,'43.3 the drill set is exactly the records behind the number');
w.drill('overdue');
ok(w.DRILL==='overdue'&&/the records behind that number|السجلات خلف/.test(sh()),'43.4 clicking opens the list in place');
w.drill('overdue');
ok(w.DRILL===null,'43.5 clicking again closes it');
w.drill('unacked');
ok(w.drillSet('unacked').length===w.myUnacked(w.ME.role).length,'43.6 each key resolves to its own set, not a generic one');
w.drill('unacked');
ok(/nothing here — which is the point|لا شيء هنا/.test((w.drill('missed'),sh()))||w.drillSet('missed').length>0,'43.7 an empty drill says so, and says why that is good');
w.drill('missed');

console.log('§44 the two figures that must read zero');
ok(typeof w.deadlinesMissed==='function'&&typeof w.deliveredNotInvoiced==='function','44.1 both are computed, not typed');
ok(/target zero|الهدف صفر/.test(sh()),'44.2 the target is printed beside each');
const missedBefore=w.deadlinesMissed().length;
const probe=w.mk({ref:'Z-1',title:'zero probe',kind:'document',owner:'U-01',role:'docs',next:'do',due:w.NOW()-2*D,allow:D});
ok(w.deadlinesMissed().length===missedBefore+1,'44.3 an item a day overdue counts as a missed deadline');
const hard=w.mk({ref:'Z-2',title:'cutoff probe',kind:'document',owner:'U-01',role:'docs',next:'do',due:w.NOW()+D,allow:D,hardCutoff:w.NOW()-3600000});
ok(w.deadlinesMissed().indexOf(hard)>-1,'44.4 …and so does anything past a hard cutoff, even if not yet due');
w.resolve(probe.id);w.resolve(hard.id);
ok(w.deadlinesMissed().length===missedBefore,'44.5 resolving clears them — the figure is live, not a tally');
const delivered=w.SHIPS.filter(x=>w.isDelivered(x));
ok(delivered.length>0&&w.deliveredNotInvoiced().length>0,'44.6 delivered shipments with no invoice event are listed');
const one=w.deliveredNotInvoiced()[0];
w.slEmit&&w.slEvAvailable()&&w.slEmit('invoice.issued',{ship:one.ref,actor:'B9'});
ok(!w.slEvAvailable()||w.deliveredNotInvoiced().every(x=>x.ref!==one.ref),'44.7 an invoice.issued event removes it from the list');
ok(w.drillSet('uninvoiced').length===w.deliveredNotInvoiced().length,'44.8 the figure and its drill-down are the same set');

console.log('§45 out of office and delegation');
w.setActor('U-01');
const mine=w.openItems().filter(x=>x.owner==='U-01').length;
ok(mine>0,'45.0 the actor owns some work');
let r=w.setOOO('U-01','U-01',3,'holiday');
ok(r.ok===false,'45.1 you cannot delegate to yourself');
r=w.setOOO('U-01','U-02',3,'');
ok(r.ok===false,'45.2 a reason is required');
r=w.setOOO('U-01','U-02',3,'annual leave, back Sunday');
ok(r.ok===true&&r.moved===mine,'45.3 every open item you own moves to the delegate at once');
ok(w.openItems().filter(x=>x.owner==='U-01').length===0,'45.4 nothing stays behind with the absent person');
ok(w.openItems().filter(x=>x.delegatedFrom==='U-01').length===mine,'45.5 each delegated item remembers who it belongs to');
ok(w.personOOO('U-01')===true&&w.oooList().length===1,'45.6 the absence is visible to the team');
w.go('s1');
ok(/out of office|إجازة/.test(sh()),'45.7 …and stated on the dashboard');
const back=w.endOOO('U-01');
ok(back.ok===true&&back.back===mine&&w.openItems().filter(x=>x.owner==='U-01').length===mine,'45.8 returning gives every item back automatically');
ok(w.openItems().every(x=>!x.delegatedFrom),'45.9 …and the delegation marks are cleared');
ok(w.historyOf('U-01').some(e=>/out of office/.test(e.what))&&w.historyOf('U-01').some(e=>/back in office/.test(e.what)),'45.10 both events are in the record');

console.log('§46 standing rules');
const warm=['deadlines missed','delivered but not invoiced','target zero','your open work moved with you — it returns automatically when you are back','the records behind that number'];
ok(warm.filter(s=>!w.T_w[s]).length===0,'46.1 every warm string has an Arabic twin');
w.setLang('ar');
ok(/الهدف صفر/.test(sh())&&/مسلَّم بلا فاتورة/.test(sh()),'46.1b AR renders');
w.setLang('en');
ok(/class="machine"/.test(sh()),'46.2 machine values LTR-isolated');
console.log('\n'+(f?('FAIL — '+f+' of '+n):('ALL PASS — '+n+' checks')));
process.exit(f?1:0);
