const fs=require('fs');const {JSDOM,VirtualConsole}=require('/home/claude/work/node_modules/jsdom');
const dom=new JSDOM(fs.readFileSync('ShopyLink_D1_Control.html','utf8'),{runScripts:'dangerously',pretendToBeVisual:true,virtualConsole:new VirtualConsole()});
const w=dom.window,d=w.document;const sh=()=>d.getElementById('shell').innerHTML;
let f=0,n=0;const ok=(c,m)=>{n++;console.log((c?'  ✓ ':'  ✗ FAIL ')+m);if(!c)f++;};
const D=w.DAY;

console.log('§12 the checklist is generated');
ok(w.requiredFor('land','export','depart').length>0,'12.1 derived from mode + direction + stage');
const L=w.requiredFor('land','export','depart').map(r=>r.code).join(',');
const S=w.requiredFor('sea','export','depart').map(r=>r.code).join(',');
ok(L!==S,'12.2 land and sea produce different lists for the same stage');
const cond=w.requiredFor('land','export','depart').filter(r=>r.when)[0];
ok(!!cond&&cond.when.length>3,'12.3 a conditional document states its condition');
const tp=w.tripById('TRP-8842');
const before=w.gateCheck('TRP-8842').missing.length;
w.addShip('TRP-8842','SL-9604','New Client');
ok(w.gateCheck('TRP-8842').missing.length>before,'12.4 adding a shipment extends the pack with its own documents');
w.attach('TRP-8842','invoice',{ship:'SL-9604'});
w.rmShip('TRP-8842','SL-9604');
ok(w.gateCheck('TRP-8842').missing.length===before,'12.5 removing it removes only its documents');
ok(tp.docs.filter(x=>x.ship==='SL-9601').length>0,'12.5b …the other shipments keep theirs');

console.log('§13 the gate');
let r=w.tryExit('TRP-8842','depart');
ok(r.ok===false&&r.missing.length>0,'13.1 a missing document refuses the exit and returns the reason');
w.voidDoc('TRP-8842',tp.docs.filter(x=>x.code==='coo'&&x.ship==='SL-9601')[0].ref,'wrong consignee');
r=w.gateCheck('TRP-8842');
ok(r.missing.length===2,'13.2 the refusal names EVERY missing document, not the first');
w.attach('TRP-8842','coo',{ship:'SL-9601'});
w.attach('TRP-8842','coo',{ship:'SL-9603'});
ok(w.gateCheck('TRP-8842').ok===true,'13.3 with everything attached the exit succeeds');
const cooRef=tp.docs.filter(x=>x.code==='coo'&&x.ship==='SL-9603'&&!x.void)[0].ref;
w.voidDoc('TRP-8842',cooRef,'signature missing');
ok(w.gateCheck('TRP-8842').ok===false&&w.gateCheck('TRP-8842').missing[0].why==='void','13.4 an attached-but-void document does not satisfy the gate');
w.attach('TRP-8842','coo',{ship:'SL-9603',expires:w.NOW()-D});
ok(w.gateCheck('TRP-8842').missing[0].why==='expired','13.5 an expired document does not satisfy it either');
w.attach('TRP-8842','coo',{ship:'SL-9603',expires:w.NOW()+30*D});
ok(w.gateCheck('TRP-8842').ok===true,'13.5b a live one does');
const live=tp.docs.filter(x=>x.code==='coo'&&x.ship==='SL-9603'&&!x.void).slice(-1)[0];
w.voidDoc('TRP-8842',live.ref,'re-checked and rejected');
ok(w.tryExit('TRP-8842','depart').ok===false,'13.6 the gate is evaluated at the moment of exit, never cached');
w.attach('TRP-8830','coo',{ship:'SL-9603'});
ok(w.gateCheck('TRP-8842').ok===false,'13.7 a document filed on another trip cannot satisfy this one');
w.attach('TRP-8842','coo',{ship:'SL-9603'});

console.log('§14 the departure pack');
const three=w.tripById('TRP-8842');
ok(three.ships.length===3,'14.0 three shipments on the trip');
w.voidDoc('TRP-8842',three.docs.filter(x=>x.code==='invoice'&&x.ship==='SL-9603')[0].ref,'wrong amount');
const miss=w.gateCheck('TRP-8842').missing;
ok(miss.some(m=>m.ship==='SL-9603'&&m.code==='invoice'),'14.1 the pack checks EVERY shipment — the third one is caught');
ok(miss[0].ship&&miss[0].code,'14.2 the refusal names the shipment, not only the document');
const empty=w.mkTrip({id:'TRP-EMPTY',mode:'land',dir:'export',route:'x',stage:'depart'});
ok(w.tryExit('TRP-EMPTY','depart').ok===false&&w.gateCheck('TRP-EMPTY').why==='no shipments','14.3 a trip with no shipments cannot depart at all');
ok(['BLOCKED','CLEARED'].indexOf(w.gateState('TRP-8842'))>-1,'14.4 the indicator is binary');
ok(w.gateState('TRP-8842')==='BLOCKED','14.4b …and it currently reads BLOCKED');
w.attach('TRP-8842','invoice',{ship:'SL-9603'});
ok(w.gateState('TRP-8842')==='CLEARED','14.5 attaching the last missing document flips it in the same tick');

console.log('§15 override');
w.voidDoc('TRP-8842',three.docs.filter(x=>x.code==='packing'&&x.ship==='SL-9602')[0].ref,'illegible');
ok(w.gateState('TRP-8842')==='BLOCKED','15.0 blocked again by a voided packing list');
w.setActor('U-02');
ok(w.overrideGate('TRP-8842',null,'the client is at the border','ops').ok===false,'15.1 only the manager may override');
w.setActor('U-00');
ok(w.overrideGate('TRP-8842',null,'','manager').ok===false,'15.2 an override demands a written reason');
ok(w.overrideGate('TRP-8842',null,'border closes in one hour, packing list follows by email','manager').ok===true,'15.2b with a reason it is granted');
const ov=w.overrides().slice(-1)[0];
ok(ov.o.by&&ov.o.at&&ov.o.reason&&ov.o.missing.length>0,'15.3 who, when, why and what was missing are all recorded');
ok(w.tripById('TRP-8842').overridden===true,'15.4 the trip stays marked as overridden');
ok(w.overrides().length>0,'15.5 overrides are listed together for weekly review');
ok(w.gateState('TRP-8842')==='CLEARED','15.5b the override clears the gate for what was missing then');
w.voidDoc('TRP-8842',three.docs.filter(x=>x.code==='coo'&&x.ship==='SL-9602')[0].ref,'expired chamber stamp');
ok(w.gateState('TRP-8842')==='BLOCKED','15.6 a document that goes missing LATER closes the gate again — the override covered only that moment');

console.log('§16 attachments are evidence');
const dd=w.attach('TRP-8830','manifest');
ok(dd.by&&dd.at,'16.1 every attachment records who and when');
w.voidDoc('TRP-8830',dd.ref,'wrong consignee');
ok(w.tripById('TRP-8830').docs.some(x=>x.ref===dd.ref&&x.void),'16.2 nothing is deleted — a wrong document is voided and stays');
const v1=w.attach('TRP-8830','loading');
const v2=w.replaceDoc('TRP-8830',v1.ref,{});
ok(v2.supersedes===v1.ref&&w.tripById('TRP-8830').docs.some(x=>x.ref===v1.ref),'16.3 replacing supersedes and keeps both');
const ex=w.attach('TRP-8830','permit',{expires:w.NOW()+5*D});
ok(Math.round(w.expiresIn(ex)/D)===5,'16.4 an expiry is carried and the days remaining are computable');

console.log('§17 standing rules');
w.go('s5');
ok(/BLOCKED|محجوبة/.test(sh())||/CLEARED|مُخلّاة/.test(sh()),'17.0 the board renders the binary state');
const warm=['a stage cannot be exited while a required document is missing — this is a refusal, not a warning','departure refused — the pack is incomplete','The documents stay missing. The override is recorded with your name and reviewed weekly.','none — the packs have been complete'];
ok(warm.filter(s=>!w.T_w[s]).length===0,'17.1 every warm string has an Arabic twin');
ok(/class="machine"/.test(sh()),'17.2 machine values LTR-isolated');
w.setLang('ar');
ok(/بوابات المستندات/.test(sh())&&/محجوبة|مُخلّاة/.test(sh()),'17.1b AR renders');
w.setLang('en');
console.log('\n'+(f?('FAIL — '+f+' of '+n):('ALL PASS — '+n+' checks')));
process.exit(f?1:0);
