// A quotation comes before a shipment. Three steps: who is asking, what the job is
// and what it costs, then a full review before it goes out.
const fs=require('fs');const {JSDOM,VirtualConsole}=require('/home/claude/work/node_modules/jsdom');
const mk=()=>new JSDOM(fs.readFileSync('ShopyLink_Action_09_Billing.html','utf8'),{runScripts:'dangerously',pretendToBeVisual:true,url:'https://x.test',virtualConsole:new VirtualConsole()}).window;
let f=0,n=0;const ok=(c,m)=>{n++;console.log((c?'  ✓ ':'  ✗ FAIL ')+m);if(!c)f++;};
let w=mk(); const d=()=>w.document; const sh=()=>d().getElementById('shell').innerHTML;
const btn=re=>[...d().querySelectorAll('#shell button')].find(b=>re.test(b.textContent.trim()));

console.log('§1 the way in');
w.go('s1');
ok(!!btn(/Create new quote/),'the billing queue offers Create new quote');
w.go('qlist');
ok(!!btn(/Create new quote/),'…and so does the quotations page, with the same name (E5)');
ok(/Quotations/.test(d().querySelector('.sec-title').textContent),'…which is titled for what it holds');

console.log('§2 step 1 — the client comes from the register');
w.go('q');
ok(d().querySelectorAll('#shell input[type=text]').length===0,'no free-text box beside the list — it would invite a second spelling');
ok(!!d().querySelector('#shell select'),'the client is chosen from the list');
ok(!/Pays|يدفع/.test(sh()),'no payment control: cash is the standing term');
ok(btn(/Next/).disabled,'Next waits for a client');

console.log('§3 registering one who is not on the list');
w.openNewClient();
const dlg=()=>{const el=d().querySelector('.sl-modal');return el?el.innerHTML:'';};
ok(/Register a client/.test(dlg()),'the button opens a dialog');
ok(d().querySelector('.sl-modal-ov').closest('#shell')===null,'…on the window, so it centres on the page and not in the 800px column');
ok(!/Company name/.test(dlg()),'an individual is not asked for a company');
w.ncKind('business');
ok(/Company name/.test(dlg())&&/Company address/.test(dlg()),'a business is asked for both');
ok((dlg().match(/<select/g)||[]).length===2,'country and city are chosen from lists, never typed');
w.ncCountry('SY');
ok(/\+963/.test(dlg())&&/Damascus/.test(dlg()),'the country sets the dialling code and the city list');
const box=d().querySelector('.sl-modal input[type=text]'); box.focus();
'Aleppo Textiles'.split('').forEach(c=>{box.value+=c; box.dispatchEvent(new w.Event('input',{bubbles:true}));});
ok(w.NC.name==='Aleppo Textiles'&&d().activeElement===box,'a whole name types and the caret stays put (C10)');
w.ncSet('phone','+963 21 555 0100'); w.ncSet('city','Aleppo'); w.ncSet('country','Syria');
ok(d().getElementById('nc-save').disabled,'save refuses without the company name');
w.ncSet('company','Aleppo Textiles LLC');
const before=w.CLIENTS.length;
d().getElementById('nc-save').click();
ok(w.CLIENTS.length===before+1,'saving puts them in the CLIENT LIST, not only in this quote');
ok(w.clientByName('Aleppo Textiles').term==='cash','…on cash terms');
ok(w.QD.cust==='Aleppo Textiles'&&w.QS===2,'…selects them and moves to the job');

console.log('§4 step 2 — the job, the cargo, the lines');
ok(/The cargo/.test(sh()),'the cargo sits under the route');
ok(/Goods/.test(sh())&&/Cartons/.test(sh())&&/Weight/.test(sh())&&/Volume/.test(sh()),'goods, cartons, weight and volume');
w.qSet('from','Guangzhou'); w.qSet('dest','Damascus'); w.qSetField('method','sea');
w.qSet('goods','cotton textiles'); w.qSet('cartons','40'); w.qSet('weight','1250'); w.qSet('volume','8.4');
ok(/40ft container/.test(sh())&&/full truck/.test(sh())&&/Parcel/.test(sh()),'carriage is priced here as well as the local services');
ok(/something else/.test(sh()),'…and a free line for anything on neither list');
w.qPickService('Sea freight — 40ft container');
ok(w.QNEW.price==='','carriage carries no list price — it moves with the market and is set per job');
w.qSetNewQuiet('price','2400'); d().getElementById('q-add').click();
ok(w.QD.lines.length===1,'+ adds the line');
ok(w.QNEW.svc===''&&/choose a service/.test(sh()),'…and a fresh line is waiting immediately');
w.qPickService('Customs clearance');
ok(w.QNEW.price==='200','a local service still fills its listed rate');
w.qSetNewQuiet('price','200'); d().getElementById('q-add').click();
w.qPickService('__free'); w.qSetNewQuiet('freeName','Fumigation certificate'); w.qSetNewQuiet('price','65');
d().getElementById('q-add').click();
ok(w.QD.lines.length===3,'a typed service can be added too');

console.log('§5 step 3 — read the whole thing before it goes');
w.qGo(3);
ok(/Aleppo Textiles/.test(sh()),'the client');
ok(/Guangzhou → Damascus/.test(sh()),'the route');
ok(/cotton textiles/.test(sh())&&/40 cartons/.test(sh())&&/1250 kg/.test(sh())&&/8.4 m³/.test(sh()),'the cargo in full');
ok(/2,400.00/.test(sh())&&/Fumigation/.test(sh()),'every priced line');
ok(/2,665.00/.test(sh()),'and the total');
ok((sh().match(/>Edit</g)||[]).length===3,'an Edit beside each part, so a wrong line is not fixed by unwinding the lot');
btn(/Edit/).click();
ok(w.QS===1,'…and it goes to the part it names');
w.qGo(3);
const q0=w.QUOTES.length;
btn(/Issue/).click();
ok(w.QUOTES.length===q0+1,'issuing mints it');
ok(w.sim==='qview','…and opens it as a document to be read before it goes anywhere');
ok(w.QUOTES[0].goods==='cotton textiles','…carrying the cargo with it');
ok(w.QUOTES[0].ship===null,'…with no shipment behind it yet');

console.log('§6 the list ends it one of two ways');
const inv0=w.INVOICES.length;
w.askQuoteWin(w.QUOTES[0].id); w.modalOk();
ok(w.INVOICES.length===inv0+1,'confirmed → the shipment is created then, not before');
w=mk(); w.go('q'); w.qSetCust('TechLine Trading'); w.qGo(2);
w.qSet('from','Istanbul'); w.qSet('dest','Damascus'); w.qSetField('method','land');
w.qPickService('Customs clearance'); w.qSetNewQuiet('price','200'); d().getElementById('q-add').click();
w.qGo(3); btn(/Issue/).click();
const inv1=w.INVOICES.length;
w.askQuoteLose(w.QUOTES[0].id); w.setTyped('client went elsewhere'); w.modalOk();
ok(w.QUOTES[0].status==='closed'&&w.INVOICES.length===inv1,'closed → nothing is created, and the reason is kept');

console.log('§7 the ordinary shipment never had a quotation');
w=mk();
ok(w.INVOICES.every(v=>!v.quoteRef),'every seeded shipment carries none, and that is normal');
const v=w.INVOICES.filter(x=>x.status==='draft')[0];
w.openInv(v.ship);
ok(sh().length>3000&&!/Quote this shipment/.test(sh()),'…and it is never asked to acquire one');

console.log('§8 the header that was broken');
v.status='issued'; v.inv_no=null; w.go('s3');
ok(!/null/.test(d().getElementById('shell').textContent),'no null where a number has not been minted');
ok(!d().getElementById('inv-bc'),'…and no empty barcode panel');
v.inv_no='INV-2608-01'; w.render();
ok((d().getElementById('inv-bc').innerHTML.match(/<rect/g)||[]).length>10,'once numbered, the barcode draws');
ok(!!d().querySelector('#inv-logo img'),'and the brand is the embedded asset (A1)');
console.log('§9 issuing and sending are two acts');
w=mk(); w.go('q'); w.openNewClient();
w.ncSet('name','Aleppo Textiles'); w.ncSet('phone','+963 21 555'); w.ncSet('email','a@b.com');
d().getElementById('nc-save').click();
w.qSet('from','Guangzhou'); w.qSet('dest','Damascus'); w.qSetField('method','sea');
w.qSet('goods','cotton textiles'); w.qSet('weight','1250');
w.qPickService('Customs clearance'); w.qSetNewQuiet('price','200'); d().getElementById('q-add').click();
w.qGo(3);
ok(/Issue the quotation/.test(sh()),'step 3 issues — it does not issue AND send in one press');
btn(/Issue/).click();
ok(w.sim==='qview'&&/QTN-/.test(sh()),'issuing shows the quotation as a document');
ok(/1250 kg/.test(sh())&&/Customs clearance/.test(sh()),'…in full, cargo and lines');
ok(!w.QUOTES[0].sentWa&&!w.QUOTES[0].sentEmail,'…and nothing has gone out yet');
ok(!!btn(/WhatsApp/)&&!!btn(/Email/)&&!!btn(/Both/),'sending is a separate choice: WhatsApp, email, or both');
btn(/WhatsApp/).click(); w.modalOk();
ok(!!w.QUOTES[0].sentWa&&!w.QUOTES[0].sentEmail,'WhatsApp records itself and does not claim the email went');
btn(/Both/).click(); w.modalOk();
ok(!!w.QUOTES[0].sentEmail,'…and it can be sent again, which is what a resend is');

console.log('§10 a client with no way to be reached');
w=mk(); w.go('q'); w.qSetCust('TechLine Trading'); w.qGo(2);
w.qSet('from','X'); w.qSet('dest','Y'); w.qSetField('method','land');
w.qPickService('Customs clearance'); w.qSetNewQuiet('price','200'); d().getElementById('q-add').click();
w.qGo(3); btn(/Issue/).click();
ok(/no phone on file/.test(sh()),'the page says which contact is missing');
ok(btn(/WhatsApp/).disabled&&btn(/Email/).disabled,'…and both channels refuse');
ok(w.sendQuote(w.QUOTES[0].id,'wa').ok===false,'…at the act, not only on the button (F18)');

console.log('§11 the cargo block fits its card');
w=mk(); w.go('q'); w.qSetCust('TechLine Trading'); w.qGo(2);
ok(/grid-template-columns:2.2fr 1fr 1fr 1fr/.test(sh()),'goods and the three measurements share one grid line');
ok(/box-sizing:border-box/.test(sh()),'…and the inputs count padding inside their width');
ok(/white-space:nowrap/.test(sh()),'…with labels that stay on one line');

console.log('§12 the client dialog, as asked for');
w=mk(); w.go('q'); w.openNewClient();
const dl=()=>{const e=d().querySelector('.sl-modal');return e?e.innerHTML:'';};
const order=dl();
ok(order.indexOf('Client name')<order.indexOf('Country'),'name first');
ok(order.indexOf('Country')<order.indexOf('Phone'),'…then country and city');
ok(order.indexOf('Phone')<order.indexOf('Email')||/Phone[\s\S]{0,900}Email/.test(order),'…then phone and email');
ok(/choose a country first/.test(dl()),'the city waits for a country to be chosen');
w.ncCountry('CN');
ok(/\+86/.test(dl()),'the dialling code follows the country: +86');
ok(/Guangzhou/.test(dl()),'…and so do its cities');
w.ncSet('name','Yiwu Trading'); w.ncSet('city','Yiwu'); w.ncSet('phone','139 0000 1111');
d().getElementById('nc-save').click();
const cc=w.clientByName('Yiwu Trading');
ok(cc&&cc.phone==='+86 139 0000 1111','the saved number carries its code: '+(cc?cc.phone:''));
ok(cc.country==='China','…and the country by name');

console.log('§13 the issued quotation offers the real sheet');
w=mk(); w.go('q'); w.qSetCust('TechLine Trading'); w.qGo(2);
w.qSet('from','Guangzhou'); w.qSet('dest','Damascus'); w.qSetField('method','sea');
w.qPickService('Customs clearance'); w.qSetNewQuiet('price','200'); d().getElementById('q-add').click();
w.qGo(3); btn(/Issue/).click();
ok(!!btn(/Open the printed sheet/),'the issued view opens the designed A4 sheet rather than a lookalike (G1)');
ok(fs.existsSync('ShopyLink_Doc_Quotation.html'),'…and that sheet exists to be opened');

console.log('§14 the confirmed quotation fills its shipment');
w=mk(); w.go('q'); w.qSetCust('TechLine Trading'); w.qGo(2);
w.qSet('from','Guangzhou'); w.qSet('dest','Damascus'); w.qSetField('method','sea');
w.qSet('goods','cotton textiles'); w.qSet('cartons','40'); w.qSet('weight','1250'); w.qSet('volume','8.4');
w.qPickService('Customs clearance'); w.qSetNewQuiet('price','200'); d().getElementById('q-add').click();
w.qGo(3); btn(/Issue/).click();
w.askQuoteWin(w.QUOTES[0].id); w.modalOk();
const nv=w.INVOICES[w.INVOICES.length-1];
ok(nv.from==='Guangzhou'&&nv.dest==='Damascus'&&nv.method==='sea','the route travels into the shipment');
ok(nv.goods==='cotton textiles','…the goods');
ok(nv.units===40&&nv.weight===1250&&nv.load===8.4,'…cartons, weight and volume, as numbers not strings');
ok(nv.lines.length===1&&nv.quoteRef===w.QUOTES[0].id,'…the agreed price and a reference back — nothing is typed twice');

console.log('§15 the client register has one owner');
const own=new JSDOM(fs.readFileSync('ShopyLink_D1_Control.html','utf8'),{runScripts:'dangerously',pretendToBeVisual:true,url:'https://x.test',virtualConsole:new VirtualConsole()}).window;
const pubc=own.slClientsRead();
ok(pubc&&pubc.length>0,'D1 publishes the client register ('+(pubc?pubc.length:0)+')');
w=mk(); w.localStorage.setItem('SL_CLIENTS_V1',own.localStorage.getItem('SL_CLIENTS_V1'));
w.CLIENTS.length=0; w.clientsSeed();
ok(w.CLIENTS.some(c=>c.id==='CL-001'),'B9 reads the owner list, keeping the owner ids');
w.addClient({name:'Aleppo Textiles',phone:'+963 21 555',kind:'business',company:'X LLC',city:'Aleppo',country:'Syria'});
ok(JSON.parse(w.localStorage.getItem('SL_CLIENTS_V1')).clients.some(c=>c.name==='Aleppo Textiles'),'…and a client registered here is pushed back to the owner');
const bare9=mk();
ok(bare9.CLIENTS.length>0,'with the bus down B9 still has clients — the work is never blocked');

console.log('§16 the quotations page respects the grant');
const c9w=new JSDOM(fs.readFileSync('ShopyLink_Action_C9_Staff.html','utf8'),{runScripts:'dangerously',pretendToBeVisual:true,url:'https://x.test',virtualConsole:new VirtualConsole()}).window;
const sreg=c9w.localStorage.getItem('SL_STAFF_V1');
const st=JSON.parse(sreg).staff;
w=mk(); w.localStorage.setItem('SL_STAFF_V1',sreg);
w.QUOTES.push({id:'QA',by:'Someone Else',customer:'A',status:'review',lines:[],validUntil:'2099-01-01'});
ok(w.quotesVisible().length===1,'with no signed-in user the list is whole — unknown is not refusal');
const pr=st.filter(p=>p.perms.indexOf('pr_agreed')>-1)[0];
const pl=st.filter(p=>p.perms.indexOf('pr_agreed')===-1)[0];
w.setActorB9(pr.id); ok(w.quotesVisible().length===1,'pricing rights see every quotation');
w.setActorB9(pl.id); ok(w.quotesVisible().length===0,'without them, only your own — and this clerk raised none');
w.QUOTES.push({id:'QB',by:pl.name,customer:'B',status:'review',lines:[],validUntil:'2099-01-01'});
ok(w.quotesVisible().length===1,'…and does see the one they raised');

console.log('§17 carriage is rate x quantity, not a lump');
w=mk(); w.go('q'); w.qSetCust('TechLine Trading'); w.qGo(2);
w.qPickService('Sea freight — LCL, per CBM');
ok(/enter the/.test(sh()),'with no volume it asks for one rather than accepting a guess');
w.qSet('volume','8.4'); w.qPickService('Sea freight — LCL, per CBM'); w.qSetRate('95');
ok(/× 8.4 m³/.test(sh())&&w.QNEW.price==='798','95 per m³ × 8.4 = 798, and the arithmetic is on screen');
w.qSet('weight','1250'); w.qPickService('Air freight — per chargeable kg'); w.qSetRate('4.2');
ok(w.QNEW.price==='5250','air: 4.2 × 1250 = 5250');
w.qPickService('Sea freight — 40ft container');
ok(!/Rate per/.test(sh()),'a container is flat — no arithmetic is imposed where none applies');
w.qSetNewQuiet('price','2400'); d().getElementById('q-add').click();
ok(w.QD.lines[0].amt===2400,'…and an agreed figure still wins');

console.log('\n'+(f?('FAIL — '+f+' of '+n):('ALL PASS — '+n+' checks')));
process.exit(f?1:0);
