const fs=require('fs');const {JSDOM,VirtualConsole}=require('/home/claude/work/node_modules/jsdom');
const dom=new JSDOM(fs.readFileSync('ShopyLink_D1_Control.html','utf8'),{runScripts:'dangerously',pretendToBeVisual:true,virtualConsole:new VirtualConsole()});
const w=dom.window,d=w.document;const sh=()=>d.getElementById('shell').innerHTML;
let f=0,n=0;const ok=(c,m)=>{n++;console.log((c?'  ✓ ':'  ✗ FAIL ')+m);if(!c)f++;};

console.log('§28 business type');
ok(w.BIZ_TYPES.length>=8,'28.1 a business-type list exists (importer, retailer, wholesaler, manufacturer, e-commerce, forwarder, contractor, other)');
ok(w.bizTypeLabel('importer').length>3,'28.2 each type has a label');
w.setLang('ar');ok(w.bizTypeLabel('importer')==='مستورد / تاجر','28.2b …in Arabic too');w.setLang('en');
ok(w.clientById('CL-001').bizType==='importer'&&w.clientById('CL-002').bizType==='wholesaler','28.3 existing businesses carry a type');

console.log('§29 contact people');
const c1=w.clientById('CL-001');
ok(c1.contacts.length===2,'29.1 a business may hold several contact people');
ok(c1.contacts[0].role==='owner'&&c1.contacts[1].role==='ap','29.2 each contact carries the role it answers for');
ok(c1.contacts[0].position&&c1.contacts[0].phone2,'29.3 a contact carries a position and a second phone');
ok(w.CONTACT_ROLES.length===4,'29.4 four roles: owner · operations · documentation · accounts payable');
ok(w.contactFor('CL-001','ap').name==='Rasha Deeb','29.5 a contact can be found by its role — the invoice knows where to go');
ok(w.contactFor('CL-002','ap')===null,'29.5b …and its absence is detectable');
let r=w.addContact('CL-002',{name:'Hiba Nour',role:'docs',position:'Documentation officer',phone:'+963 933 444 555'});
ok(r.ok===true&&w.clientById('CL-002').contacts.length===2,'29.6 a contact can be added');
r=w.addContact('CL-002',{name:'No Way'});
ok(r.ok===false&&r.need.indexOf('phone or email')>-1,'29.7 a contact needs a phone or an email — nothing less');
r=w.addContact('CL-002',{role:'ops',phone:'+963 1'});
ok(r.ok===false&&r.need.indexOf('contact name')>-1,'29.7b …and a name');
r=w.rmContact('CL-002',0,'left the company');
ok(r.ok===true&&w.clientById('CL-002').contacts.length===1,'29.8 a contact can be removed with a reason');
r=w.rmContact('CL-002',0,'the last one');
ok(r.ok===false&&/at least one/.test(r.why),'29.9 the LAST contact cannot be removed — a client is never left unreachable');
r=w.rmContact('CL-001',1,'');
ok(r.ok===false,'29.10 removal without a reason is refused');

console.log('§30 completion demands the business identity');
const nb=w.quickCreate({name:'Fresh Import Co',country:'Syria',contact:'Samer',phone:'+963 966 555 444',type:'business'});
ok(nb.ok===true&&w.clientById(nb.id).status==='PROVISIONAL','30.1 quick create is still four fields — operations is not held up');
ok(!w.clientById(nb.id).bizType,'30.1b …and the business type is NOT demanded at that moment');
let cr=w.completeProfile(nb.id,{tax:'SY-1',address:'Damascus'});
ok(cr.ok===false&&cr.need.indexOf('business type')>-1,'30.2 completion refuses a business with no type');
cr=w.completeProfile(nb.id,{tax:'SY-1',address:'Damascus',bizType:'importer'});
ok(cr.ok===false&&cr.need.some(x=>/contact person/.test(x)),'30.3 …and refuses one whose contact has no role');
cr=w.completeProfile(nb.id,{tax:'SY-1',address:'Damascus',bizType:'importer',contactRole:'owner',position:'Owner'});
ok(cr.ok===true&&w.clientById(nb.id).status==='ACTIVE','30.4 with both, it goes ACTIVE');
ok(w.clientById(nb.id).bizType==='importer'&&w.clientById(nb.id).contacts[0].role==='owner','30.4b …and both are stored');
const ni=w.quickCreate({name:'Walid Person',country:'Syria',contact:'Walid',phone:'+963 900 000 001',type:'individual'});
ok(w.completeProfile(ni.id,{tax:'SY-2',address:'Homs'}).ok===true,'30.5 an individual is not asked for a business type — the rule applies to businesses only');

console.log('§31 the derived rule: credit needs somebody to invoice');
ok(w.creditContactGap('CL-001')===false,'31.1 a business with credit AND an accounts-payable contact is fine');
w.setActor('U-00');
let g=w.grantCredit('CL-002',30,2000,'good history','manager');
ok(g.ok===false&&/accounts-payable/.test(g.why),'31.2 credit CANNOT be granted with no accounts-payable contact — prevented at the source, not flagged afterwards');
w.addContact('CL-002',{name:'Rami Accounts',role:'ap',phone:'+963 933 000 111'});
g=w.grantCredit('CL-002',30,2000,'good history','manager');
ok(g.ok===true&&w.creditContactGap('CL-002')===false,'31.3 with the contact in place it is granted, and no gap is flagged');
w.rmContact('CL-002',w.clientById('CL-002').contacts.findIndex(k=>k.role==='ap'),'the accountant left');
ok(w.creditContactGap('CL-002')===true,'31.3b if that contact later LEAVES, the gap flag fires — an invoice with nobody to send it to');
ok(w.creditContactGap('CL-003')===false,'31.4 an individual is never flagged — it has no credit at all');

console.log('§32 standing rules');
w.go('s7');
ok(/contact people|جهات الاتصال/.test(sh()),'32.0 the card lists the contact people');
ok(/Accounts payable|Owner|الحسابات|المالك/.test(sh()),'32.0b …each with its role');
ok(/importer|Importer|مستورد/.test(sh()),'32.0c and the business type is shown');
const warm=['contact people','business type','a business account needs its type and a contact person with a role before it can go active','credit granted with no accounts-payable contact','A client must always keep at least one. The removal is logged.'];
ok(warm.filter(s=>!w.T_w[s]).length===0,'32.1 every warm string has an Arabic twin');
w.setLang('ar');
ok(/جهات الاتصال/.test(sh())&&/مستورد|تاجر جملة/.test(sh()),'32.1b AR renders — the card shows the TYPE VALUE, and the words appear only when it is missing');
const prov=w.quickCreate({name:'AR Gap Co',country:'Syria',contact:'q',phone:'+963 900 111 222',type:'business'});w.render();
ok(/نوع النشاط غير محدَّد/.test(sh()),'32.1c …a business with no type says so, in Arabic');
w.setLang('en');
console.log('\n'+(f?('FAIL — '+f+' of '+n):('ALL PASS — '+n+' checks')));
process.exit(f?1:0);
